// cryptologos.cc filenames don't always match the ticker (e.g. XAUT is
// "tether-gold-xaut-logo.png", not "xaut-xaut-logo.png"). Verify a new
// entry resolves with a HEAD request before adding it here.
const COIN_LOGOS = {
    btc: 'bitcoin-btc-logo.png',
    eth: 'ethereum-eth-logo.png',
    bnb: 'bnb-bnb-logo.png',
    sol: 'solana-sol-logo.png',
    xrp: 'xrp-xrp-logo.png',
    doge: 'dogecoin-doge-logo.png',
    ada: 'cardano-ada-logo.png',
    avax: 'avalanche-avax-logo.png',
    dot: 'polkadot-new-dot-logo.png',
    matic: 'polygon-matic-logo.png',
    link: 'chainlink-link-logo.png',
    uni: 'uniswap-uni-logo.png',
    atom: 'cosmos-atom-logo.png',
    ftm: 'fantom-ftm-logo.png',
    near: 'near-protocol-near-logo.png',
    apt: 'aptos-apt-logo.png',
    arb: 'arbitrum-arb-logo.png',
    op: 'optimism-ethereum-op-logo.png',
    sui: 'sui-sui-logo.png',
    xaut: 'tether-gold-xaut-logo.png',

    // Stablecoins
    usdt: 'tether-usdt-logo.png',
    usdc: 'usd-coin-usdc-logo.png',
    busd: 'binance-usd-busd-logo.png',
    dai: 'multi-collateral-dai-dai-logo.png',
    tusd: 'trueusd-tusd-logo.png',
    usdd: 'usdd-usdd-logo.png',
    paxg: 'pax-gold-paxg-logo.png',

    // Large caps / L1s
    ton: 'toncoin-ton-logo.png',
    trx: 'tron-trx-logo.png',
    shib: 'shiba-inu-shib-logo.png',
    ltc: 'litecoin-ltc-logo.png',
    bch: 'bitcoin-cash-bch-logo.png',
    leo: 'unus-sed-leo-leo-logo.png',
    etc: 'ethereum-classic-etc-logo.png',
    xlm: 'stellar-xlm-logo.png',
    xmr: 'monero-xmr-logo.png',
    okb: 'okb-okb-logo.png',
    fil: 'filecoin-fil-logo.png',
    hbar: 'hedera-hbar-logo.png',
    vet: 'vechain-vet-logo.png',
    icp: 'internet-computer-icp-logo.png',
    imx: 'immutable-x-imx-logo.png',
    inj: 'injective-inj-logo.png',
    egld: 'multiversx-egld-egld-logo.png',
    flow: 'flow-flow-logo.png',
    theta: 'theta-network-theta-logo.png',
    eos: 'eos-eos-logo.png',
    xtz: 'tezos-xtz-logo.png',
    kava: 'kava-kava-logo.png',
    neo: 'neo-neo-logo.png',
    kda: 'kadena-kda-logo.png',
    rose: 'oasis-network-rose-logo.png',
    cfx: 'conflux-network-cfx-logo.png',
    sei: 'sei-sei-logo.png',
    tia: 'celestia-tia-logo.png',
    stx: 'stacks-stx-logo.png',
    ksm: 'kusama-ksm-logo.png',
    one: 'harmony-one-logo.png',
    iota: 'iota-iota-logo.png',
    qtum: 'qtum-qtum-logo.png',
    waves: 'waves-waves-logo.png',
    dash: 'dash-dash-logo.png',
    zec: 'zcash-zec-logo.png',
    ordi: 'ordi-ordi-logo.png',
    tao: 'bittensor-tao-logo.png',
    akt: 'akash-network-akt-logo.png',

    // DeFi / infra
    grt: 'the-graph-grt-logo.png',
    mkr: 'maker-mkr-logo.png',
    aave: 'aave-aave-logo.png',
    algo: 'algorand-algo-logo.png',
    qnt: 'quant-qnt-logo.png',
    ldo: 'lido-dao-ldo-logo.png',
    rune: 'thorchain-rune-logo.png',
    crv: 'curve-dao-token-crv-logo.png',
    snx: 'synthetix-snx-logo.png',
    comp: 'compound-comp-logo.png',
    cake: 'pancakeswap-cake-logo.png',
    '1inch': '1inch-1inch-logo.png',
    yfi: 'yearn-finance-yfi-logo.png',
    ankr: 'ankr-ankr-logo.png',
    zrx: '0x-zrx-logo.png',
    lrc: 'loopring-lrc-logo.png',
    bal: 'balancer-bal-logo.png',
    woo: 'wootrade-woo-logo.png',
    dydx: 'dydx-chain-dydx-logo.png',
    ens: 'ethereum-name-service-ens-logo.png',
    cvx: 'convex-finance-cvx-logo.png',
    rpl: 'rocket-pool-rpl-logo.png',
    pyth: 'pyth-network-pyth-logo.png',
    strk: 'starknet-token-strk-logo.png',

    // NFT / gaming / metaverse
    sand: 'the-sandbox-sand-logo.png',
    mana: 'decentraland-mana-logo.png',
    axs: 'axie-infinity-axs-logo.png',
    kas: 'kaspa-kas-logo.png',
    gala: 'gala-gala-logo.png',
    ape: 'apecoin-ape-ape-logo.png',
    enj: 'enjin-coin-enj-logo.png',
    hot: 'holo-hot-logo.png',
    rvn: 'ravencoin-rvn-logo.png',
    bat: 'basic-attention-token-bat-logo.png',
    zil: 'zilliqa-zil-logo.png',
    omg: 'omg-omg-logo.png',
    mina: 'mina-mina-logo.png',

    // Newer / meme
    pepe: 'pepe-pepe-logo.png',
    wld: 'worldcoin-org-wld-logo.png',
    fet: 'artificial-superintelligence-alliance-fet-logo.png',
    wif: 'dogwifhat-wif-logo.png',
    bonk: 'bonk1-bonk-logo.png',
    floki: 'floki-inu-floki-logo.png',
    jup: 'jupiter-ag-jup-logo.png',
    ftt: 'ftx-token-ftt-logo.png',
    xec: 'ecash-xec-logo.png',
};

function getCoinLogoUrl(shortSymbol) {
    const file = COIN_LOGOS[shortSymbol.toLowerCase()] || COIN_LOGOS.btc;
    return `https://cryptologos.cc/logos/${file}`;
}
